CXX=g++
INCLUDEDIR=../include

LINK.o = $(LINK.cc)

#CXXFLAGS=-g -fPIC -Wall -std=c++11 -Wno-unused-function -Wno-write-strings -Wno-invalid-offsetof -Wno-parentheses -I$(INCLUDEDIR) -I/usr/include -I/usr/include/mysql

CXXFLAGS=-DNDEBUG -O3 -fPIC -Wall -std=c++11 -Wno-unused-function -Wno-write-strings -Wno-invalid-offsetof -Wno-parentheses -I$(INCLUDEDIR) -I/usr/include -I/usr/include/mysql

LDLIBS = -lpthread -ldl
